# site settings
title: Reaktivity
description: High performance, shared memory microservices
baseurl: ""
url: ""
google_analytics: UA-92246880-1

# build settings
theme: jekyll-theme-architect
permalink: /articles/:title/
markdown: kramdown
highlighter: rouge
defaults:
  - scope:
      path: ""
    values:
      layout: "default"
excerpt_separator: "[//]: # (more)"
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - CNAME

# development settings
livereload: true
